name: Go CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Install dependencies
      run: go mod tidy

    - name: Build the project
      run: go build -v ./...
      
    - name: Run Go Lint (Optional)
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...
